###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mongo:
      image: mongo
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
        MONGO_INITDB_DATABASE: admin
        MONGO_USERNAME: daudq
        MONGO_PASSWORD: root
      ports:
        - "27017:27017"
      volumes:
        - ./mongo-entrypoint.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      command: mongod
    
    # mongo-express:
    #   image: mongo-express
    #   restart: always
    #   ports:
    #     - 9081:8081
    #   environment:
    #     - ME_CONFIG_MONGODB_ADMINUSERNAME=root
    #     - ME_CONFIG_MONGODB_ADMINPASSWORD=root
    #     - ME_CONFIG_BASICAUTH_USERNAME=daudq
    #     - ME_CONFIG_BASICAUTH_PASSWORD=root

    webserver:
      # image: nginx:alpine
      build: phpdocker/nginx
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
          - ./phpdocker/nginx/certs:/etc/nginx/certs
      ports:
       - "80:80"
       - "443:443"
      links:
        - mongo
        - mailcatcher
        - redis
        - php-fpm
      environment:
        - PMA_HOST=mongo

    php-fpm:
      # container_name: "gamonishop-phpfpm"
      build: phpdocker/php-fpm
      restart: always
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/cli/conf.d/99-overrides.ini
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/mods-available/99-overrides.ini
        #- ./phpdocker/supervisor/laravel-worker.conf:/etc/supervisor/conf.d/laravel-worker.conf
      links:
        - mongo
        - redis
        - mailcatcher
      environment:
        - PMA_HOST=mongo

    rockmongo:
      image: weshigbee/rockmongo
      working_dir: /application
      links:
       - mongo
       - php-fpm
      environment:
        - MONGO_SERVER=mongo
        - MONGO_PORT=27017
        - MONGO_DATABASE=admin
        - MONGO_AUTH=true
        - MONGO_USERNAME=root
        - MONGO_PASSWORD=root
        - ROCKMONGO_AUTH=true
        - ROCKMONGO_USER=daudq
        - ROCKMONGO_PASSWORD=root
      ports:
      - "8184:80"

    redis:
      image: 'bitnami/redis:latest'
      restart: always
      environment:
        - ALLOW_EMPTY_PASSWORD=yes

    mailcatcher:
      image: schickling/mailcatcher
      ports:
       - "1084:1080"
       - "1029:1025"
